// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkrd_oum2rnarUTYPvCKyoHuaVltSz4d8',
    appId: '1:816897717642:android:81c0eb9a0f944c87294473',
    messagingSenderId: '816897717642',
    projectId: 'fir-6e075',
    storageBucket: 'fir-6e075.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9dMRFV4QTFB_7Wlxi4e4mIY9aBo9f1Pk',
    appId: '1:816897717642:ios:c260a401dee35410294473',
    messagingSenderId: '816897717642',
    projectId: 'fir-6e075',
    storageBucket: 'fir-6e075.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQjsDMpf7UaphJeZ9a6VV5hT05RiHQpbc',
    appId: '1:816897717642:web:d336a7ff4107d14e294473',
    messagingSenderId: '816897717642',
    projectId: 'fir-6e075',
    authDomain: 'fir-6e075.firebaseapp.com',
    storageBucket: 'fir-6e075.firebasestorage.app',
    measurementId: 'G-VFTCB7E9CL',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQjsDMpf7UaphJeZ9a6VV5hT05RiHQpbc',
    appId: '1:816897717642:web:3b9e0fdf33e70b99294473',
    messagingSenderId: '816897717642',
    projectId: 'fir-6e075',
    authDomain: 'fir-6e075.firebaseapp.com',
    storageBucket: 'fir-6e075.firebasestorage.app',
    measurementId: 'G-HWSPM071WD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9dMRFV4QTFB_7Wlxi4e4mIY9aBo9f1Pk',
    appId: '1:816897717642:ios:c260a401dee35410294473',
    messagingSenderId: '816897717642',
    projectId: 'fir-6e075',
    storageBucket: 'fir-6e075.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

}